### ISSUE TITLE
source ships with unused file COPYING

### ISSUE THREAD

**Issue by jonassmedegaard** [mirukana/mirage#132]
Source contains file <COPYING> which contains the GPL-3 license, but nothing in the project is licensed by that license.

**Comment by jonassmedegaard** [comment]
I notice now that even though this project is licensed LGPL-3-or-newer it links with QSyncable which is licensed Apache-2.0, so the effective license of binary code becomes GPL-3-or-newer.

I suggest to add a notice in <README.md> about those licensing implications.

**Comment by mirukana** [comment]
The [COPYING.LESSER](https://github.com/mirukana/mirage/blob/master/COPYING.LESSER) file extends COPYING with LGPL additions, having them both is the recommended way to use LGPL for a project.

Concerning QSyncable, we don't use it anymore since Mirage 0.5.0, it only remains in the submodules folder to not break building older commits. 

The Apache license is compatible both with the GPL and LGPL. In addition, Apache is more permissive than LGPL, which is more permissive than GPL, so there is no reason combining the two would result in a GPL binary.

**Comment by jonassmedegaard** [comment]
Thanks for the explanation
