### ISSUE TITLE
"MIT-SCREEN-SAVER missing" message is being constantly printed to stdout

### ISSUE THREAD

**Issue by greenfoo** [mirukana/mirage#155]
### Description

When running from the command line, the following message is constantly being spammed to stdout (~ once per second)
```
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".
...
```

### Your environment

- Arch Linux
- x86 64bit
- GNOME 3.38.1 Wayland
- Flatpak package

### Steps to reproduce

1. Run `mirage`
2. Look at stdout

### Expected behavior

Error message is not printed or (maybe) printed only once

### Actual behavior

Error message is constantly being printed every second or so

**Comment by mirukana** [comment]
This happens due to the XScreenSaver library (used to check the machine's idle time for auto-away) being available, but unable to work within XWayland. Can you try https://github.com/mirukana/mirage/commit/8131503d554ce004501ab7da5785330d2ccb25b9?

**Comment by pp3345** [comment]
I haven't tested the patch, however, this generally doesn't look like a proper solution to me. Mirage can run as a native Wayland application and should not try to open an X11 display at all in this case. Some Wayland compositors (e.g., mutter in the future) are capable of starting XWayland on demand, so in this case, Mirage would cause XWayland to start and stop each time it checks for the idle time, causing additional overhead (which is probably worse than the log spam).

**Comment by mirukana** [comment]
Qt programs in a Wayland environment will always start under XWayland, unless an [option or environment variable](https://wiki.archlinux.org/index.php/wayland#Qt_5) to not do so is used. I'm sure the Qt developers have good reasons to make this the default behavior, so I'm not willing to try to override that.

The timer that checks for system idle time will immediatly stop running if the idle time retrieval function returns an invalid reponse (`-1`), so no need to worry about constant overhead.

Unfortunately, Wayland doesn't have any API to check the idle time and the only way to poll for keyboard/mouse activity would be reading the files in `/dev/input`, which requires the user to be in the `input` group; so I don't know when features relying on this like auto-away will ever work.
Another future possibility is to add running processes detection, so that the user can configure e.g. a detected screenlocker to change their presence and/or status until that process exits.

**Comment by pp3345** [comment]
This may be true for Arch, however, Fedora started using Qt's Wayland backend by default quite a while ago. In any case, it's bad style to try to invoke X11 features in a Wayland session.

mutter has a D-Bus interface to retrieve the idle time that also works in Wayland sessions: https://gitlab.gnome.org/GNOME/mutter/-/blob/master/src/org.gnome.Mutter.IdleMonitor.xml

**Comment by mirukana** [comment]
I guess we could check if `WAYLAND_DISPLAY` is defined, but note that the compiled code will always at least try to include the XScreenSaver lib if it was present at compile time and the `no-x11` option wasn't passed (as described in [`INSTALL.md`](https://github.com/mirukana/mirage/blob/master/INSTALL.md#manual-installation)).

There are a bunch of workarounds for specific environments (like the mutter dbus thing or swayidle), but as far as I know, they're just that: environment-specific workarounds, and every one of them is gonna require more dependencies and C++ code (which we try to keep to a minimum in this project).

**Comment by greenfoo** [comment]
I tried both "solutions":
* Forcing mirage to run in wayland with "QT_QPA_PLATFORM=wayland"
* Using this new commit (8131503)

In both cases the error message disappears.

(By that way, as a single data point, I've testing mirage in "wayland mode" for a few minutes and everything seems to work ok)

**Comment by mirukana** [comment]
Merged fixes into dev: https://github.com/mirukana/mirage/commit/fddf915b451f0a28261d9d64f80072b0de91493d and https://github.com/mirukana/mirage/commit/fbd615bfc2bac6e75fefd043fb70e3761beb70e7
