### ISSUE TITLE
Option to not send typing notifications

### ISSUE THREAD

**Issue by BurnyBoi** [mirukana/mirage#157]

**Comment by shunlog** [comment]
There's the "invisible" state that stops typing notifications from being sent, although I'm not sure how that affects other functionality, an option might still be useful. I guess the check for that should be made [here](https://github.com/mirukana/mirage/blob/9ac4cd0a97f76a364908aadfc3ba3d2242b2c531/src/backend/matrix_client.py#L1286)?

**Comment by mirukana** [comment]
The invisible state marks your as offline for others, prevents typing notifications and prevent your read markers from getting updated (https://github.com/mirukana/mirage/issues/56 should be implemented instead, but the problem is there's no way to know if the server supports the feature). 

You're right about the check; I'm currently reworking the config so I will add this option (and probably #56 too) after unless someone makes a PR already.

**Comment by mirukana** [comment]
Added in c06ec439fb6808b2190333d770eebfdabf8f64df to the new config file, see [documentation](https://github.com/mirukana/mirage/blob/c06ec439fb6808b2190333d770eebfdabf8f64df/docs/CONFIG.md) and [example](https://github.com/mirukana/mirage/blob/c06ec439fb6808b2190333d770eebfdabf8f64df/src/config/settings.py#L125).
