### ISSUE TITLE
PageUp and PageDown don't work with kinetic scrolling disabled

### ISSUE THREAD

**Issue by ISSOtm** [mirukana/mirage#166]
### Description

Disabling kinetic scrolling makes the PageUp and PageDown keys not do anything.

### Your environment

- Arch Linux
- x86_64
- i3 4.19
- [AUR](https://aur.archlinux.org/packages/matrix-mirage/)
- Qt 5.15.2
- Python 3.9.0

### Steps to reproduce

Set `enableKineticScrolling` to `false` in `settings.json`

### Expected behavior

The view should scroll by one screenful when pressing PageUp or PageDown

### Actual behavior

The scroll bar shows up for a second, but the view does not scroll.

**Comment by mirukana** [comment]
Can you confirm if https://github.com/mirukana/mirage/commit/0a568c807cd091b7e27946e89f67f4f2d4e9a0bf fixes the issue for you? Note that the dev branch uses a [new configuration file](https://github.com/mirukana/mirage/blob/dev/docs/CONFIG.md#settingspy), kinetic scrolling will need to be disabled there.

**Comment by ISSOtm** [comment]
Yep, PageUp/PageDown do scroll again, however re-pressing the key while still scrolling tends to send the screen flying, I guess because momentum still gets accumulated?

**Comment by ISSOtm** [comment]
I don't know if it's related, but despite having kinetic scrolling disabled in `settings.json` (and not overridden in `settings.gui.json`), it's still present.

**Comment by mirukana** [comment]
`settings.json` is not taken into account anymore, did you mean kinetic scrolling is still present despite disabling it in `settings.py`? Only when you scroll by keyboard, or for mouse/trackpad too? 

If it's only for keyboard scrolling, the [current code](https://github.com/mirukana/mirage/blob/f73c4c6/src/gui/Utils.qml#L414) makes a bunch of assumptions and doesn't support non-kinetic, so that would be a different issue. 

> Yep, PageUp/PageDown do scroll again, and by a reasonable amount at least on my 1080p screen; however re-pressing the key while still scrolling tends to send the screen flying, I guess because momentum still gets accumulated?

This is also a separate issue from the code above: to ease scrolling long distances by keyboard while still allowing small once-off taps, the function will switch to a faster mode if the current scrolling velocity is past a certain threshold. It should be improved to provide gradual acceleration instead. You can try playing with the `kinetic_max_speed` and `kinetic_max_deceleration` settings, since they will always apply to keyboard scrolling due to what I said above.

**Comment by ISSOtm** [comment]
There is no `settings.py` in `~/.config/mirage`, the folder that "Open config folder" opens. There are only `.lock`, `accounts.json`, `settings.gui.json`, and `settings.json`.

**Comment by mirukana** [comment]
Python files aren't easily machine-writable, so making a converter that can also detect which settings.json setting was actually modified from previous version defaults would be too much code. I added a warning popup if settings.json is found since f7e270ec3c8e4b7614a7baa71a263c13dcd81776.
