### ISSUE TITLE
AttributeError: 'Composer' object has no attribute 'TypingNotifications' when typing a message

### ISSUE THREAD

**Issue by ISSOtm** [mirukana/mirage#178]
### Description

```
@<username>.room_typing.<id>

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 91, in on_done
    result = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 1316, in room_typing
    rules   = self.backend.settings.Chat.Composer.TypingNotifications,
  File "qrc:/src/backend/pcn/section.py", line 69, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'Composer' object has no attribute 'TypingNotifications'
```

This started occurring after updating Mirage, and persists across reboots. (I hope that you will understand that I censored `<username>` and `<id>`.)

### Your environment

- `uname -srm`: `Linux 5.10.7-arch1-1 x86_64` (Arch Linux)
- `i3 version 4.19 (2020-11-15)`
- [`matrix-mirage-git` on AUR](https://aur.archlinux.org/packages/matrix-mirage-git/), currently at `r2432.d1a5752b-1`
- Qt 5.12.2
- Python 3.9.1

### Steps to reproduce

1. Open Mirage
2. Start typing, this error will pop up once or twice per character typed.

**Comment by mirukana** [comment]
Can you post your full settings.py?

**Comment by ISSOtm** [comment]
[`cat .config/mirage/settings.py | grep -v '^ *#' | grep -v '^$' >/tmp/settings.txt`](https://github.com/mirukana/mirage/files/5837978/settings.txt)

(TXT because GitHub otherwise rejects the file)

**Comment by mirukana** [comment]
As mentioned in the doc, it's not recommended to just copy the default file because it is bound to change between mirage versions and updates, and then you'll end up with settings that don't work because they've actually been renamed, collisions when default keybinds are changed or stuff like that. 

At least, you should have a `self.include_builtin("config/settings.py")` line at the top, so that it sources the built-in config which contains the new setting that you get an error for.

**Comment by ISSOtm** [comment]
Right, I was still referring to `master`'s README, which is outdated.
