### ISSUE TITLE
Unexpected Error: MatrixError, when trying to type something

### ISSUE THREAD

**Issue by PrivacyDragon** [mirukana/mirage#188]
### Description

Every time when I type something, for every character an error popup shows. 
I can then check the box to hide the error until restart, but I have to click it away ten times, because I always forget that it will come.

error log:

**Unexpected error occured: _MatrixError_**
```
@privacy_dragon:privacytools.io.room_typing.9b438d4e-b722-475d-930f-6849b5bf6e50

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 83, in on_done
    result = future.result()
  File "/tmp/.mount_MiragevNvabc/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/tmp/.mount_MiragevNvabc/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 1294, in room_typing
    await super().room_typing(room_id, typing_state, timeout)
  File "/tmp/.mount_MiragevNvabc/usr/lib/python3.8/site-packages/nio/client/async_client.py", line 2308, in room_typing
    return await self._send(
  File "qrc:/src/backend/matrix_client.py", line 255, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (500, 'M_UNKNOWN')
```

### Your environment

- OS: OpenSuse Leap 15.1
- Architecture: 64 bit. x86_64
- desktop environment: KDE / Plasma
- How did you install Mirage? : AppImage

### Steps to reproduce

1. Open Mirage
2. Type a message somewhere

### Expected behavior

Just being able to type a message and send it

### Actual behavior

You get an error. as noted above.
I don't know if anything is wrong on my side?

**Comment by mirukana** [comment]
This is a problem with the privacytools server (purposely?) failing to respond to a standard matrix API.  I really suggest to move away from it, because it has been dying for the past months. 

I would rather not add special error handlers for particular cases of broken servers: typing notifications are supposed to always work, so the user should know if something is up, and since "MatrixError" is a generic error that can happen anywhere for any reason, it is shown using the generic error popup -- popup that can spawn anywhere, without having to implement special UI logic for every action that triggers server requests.

However, it's true that we should prevent the popup spam: #189
