### ISSUE TITLE
System font size

### ISSUE THREAD

**Issue by piegamesde** [mirukana/mirage#190]
I have set enlarged font in my Gnome settings. I'd like for Mirage to respect this.

**Comment by mirukana** [comment]
Qt programs don't have access to GTK settings, mirage also uses more than one font size for different elements. You can control fonts using a custom theme, or the application scale with ctrl +/-/= or the config file's `General.zoom` property.

**Comment by piegamesde** [comment]
There are settings for font sizes indeed, but those are not that important. The more important setting is the font scaling factor. It can be queried over gdbus, using gsettings or the [xdg desktop portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Settings).

**Comment by mirukana** [comment]
Since Mirage is a Qt program, it uses [the Qt way](https://wiki.archlinux.org/index.php/HiDPI#Qt_5) of setting scaling. 

All GUI toolkits have different ways of taking settings, if you use a DE with some kind of control panel, it should do the work to make programs using the most common ones work properly; instead of every application having to implement some complicated logic to detect every other possible environment and their settings -- especially when GNOME/GTK goes out of its way to complicate everything with dbus and a registry, instead of universal environment variables and config files.
