### ISSUE TITLE
Kinetic scrolling is not behaving properly on trackpad

### ISSUE THREAD

**Issue by toger5** [mirukana/mirage#22]
It is nice to see kinetic scrolling.
On my setup:
 - flatpak installation
 - sway window manager
 - wayland protocol (not xwayland)
 - macbook trackpad (early 2015)
 - fedora 31

I get the following behavior:
without any input the friction seems to work fine.
With input i get really bad results. the first input/velocity is picked up. But after that i jumps into kinetic mode and variations in speed almost take no effect. A change in direction though does.
of course this also could be a QT issue.

**Comment by mirukana** [comment]
Can you paste this in a new file and run it with `qml <filename>`?
```
import QtQuick 2.12
import QtQuick.Controls 2.12

ApplicationWindow {
    width: 640
    height: 480
    visible: true

    ListView {
        id: listView
        anchors.fill: parent
        model: 1000

        delegate: Text {
            text: modelData
            font.pixelSize: 24
            width: listView.width
        }
    }
}
```
If the problem does happen here, this is definitely a Qt issue. Maybe [this](https://bugreports.qt.io/browse/QTBUG-56075)?

**Comment by toger5** [comment]
I did not yet get to run the qt example you postet. Did not have time to isntall the toolchain on my pc.
So if someone else can test this would be great.

**Comment by toger5** [comment]
The issue you linked: [QT flickable issue](https://bugreports.qt.io/browse/QTBUG-56075) sounds very similar to the problem i am having.
Did you check the last comment in the discussion? There is an implementation that he describes as resonable.

**Comment by mirukana** [comment]
Someone reported me good results with that solution, so I'll see if I can integrate it in Mirage. However, it will need to be an opt-in option, until we move to Qt 5.15 which comes with the new [WheelHandler](https://doc.qt.io/qt-5/qml-qtquick-wheelhandler.html) component that can detect the user's input device, since we don't want to apply this to mouse or touch.

**Comment by toger5** [comment]
This sounds great! When will the project switch to Qt 5.15 ?
This is the only real issue I have with using it on a laptop.

**Comment by mirukana** [comment]
5.15 is currently in beta, it should release in may if I remember correctly. After that, we have to wait until it's packaged in most common distros, which can take several months.

**Comment by toger5** [comment]
How long does that take for the flatpak version. Than everyone can use it ;)

**Comment by vSLG** [comment]
@toger5, does #43 solve your scrolling issue?

**Comment by mirukana** [comment]
> How long does that take for the flatpak version. Than everyone can use it ;)

Sorry for the late response, I had completely missed this comment. 

While we can bundle a recent Qt in the flatpak and appimages, not everyone wants to use them, and that still doesn't make us able to use new features in the code as long as it needs to remain compatible with 5.12.
If we try to import `WheelHandler` (which is only available in 5.14+) in QML, the app would just crash for users still using 5.12/13, and QML doesn't allow conditional imports like you could do in Python.

I'll close this since #43 should be the solution for now, you can comment if you still have issues with it.

**Comment by toger5** [comment]
Is it possible to implement it only for flatpak than and make flatpak use 5.14 or would that introduce so many changes that you than have to maintain two codebases?

**Comment by mirukana** [comment]
I would have at least to maintain two different files for the same component and have the right file be built in the binary depending on which Qt version  is used at compile time. It also wouldn't work at all for development builds where the "packing QML files and other resources inside the binary" part is skipped (for faster compile times).

**Comment by travankor** [comment]
Apologies for not spotting this issue.

Mirage is currently packaged for flatpak, aur, and there's a tentative one for void. So does it make sense to wait for distros like Debian and CentOS to update to Qt5.15 if no one from those communities use mirage? Something to keep in mind is that people on stable distros don't usually upgrade to the newest stable branch right away anyway, so this requirement might not be that useful as flatpak. Also mirage is still pretty new and pre-1.0 so it's sorta self-selects for people who are on rolling-release distros or who are ok with not yet 100% stable software.

I think it makes to sense to wait for Fedora (even though Redhat/Fedora recommend flatpak for these use-cases), Ubuntu-unstable, Gentoo, and NixOS stable to update to QT5.15, mostly because these are the stable distros with users that would want to try mirage.

**Comment by mirukana** [comment]
I agree with those points, I certainly don't want to wait years for distros like Debian or CentOS to offer Qt 5.15.
Users on them should be able to use the appimage and flatpak releases just fine, for development and manual installation I guess we can just link to the docs for building a recent Qt.

I'd like to at least have support for the other distros in the INSTALL.md: Arch and Void already have 5.15, Gentoo has it in testing, Ubuntu will get a PPA, but I don't know when things will move for Fedora and Alpine (if someone knows more about the subject?).

**Comment by travankor** [comment]
Alpine recently updated to QT5.15.

Fedora 33, which should have QT5.15, releases in October.

**Comment by travankor** [comment]
Gentle ping for this issue ?

**Comment by mirukana** [comment]
- It seems like Fedora 33 will come out at the end of this month
- We still need to get on Flathub (#1), so that people on distros without Qt 5.15 running other archs than x86-64 have an easy way to get the program running
