### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by rinigus** [mirukana/mirage#5]
In GNOME, I am getting constantly notifications with "Mirage ready". Would be great to get rid of it.

**Comment by mirukana** [comment]
Can you explain in more details about the "Mirage ready" notification, or post a screenshot?
Does it still happen if you set `alertOnMessageForMsec` to `0` in the config file?

**Comment by rinigus** [comment]
Haven't tested 0 in settings. But I will try to catch notification message first.

**Comment by rinigus** [comment]
Here is the screenshot

![Screenshot from 2020-03-24 11-39-31](https://user-images.githubusercontent.com/15706605/77411017-7dcfa800-6dc4-11ea-900f-7e2b352faa5b.png)

**Comment by mirukana** [comment]
Since desktop notifications aren't implemented yet, as a simple alternative by default Mirage activates the urgency hint, which highlights the taskbar/panel's related window or desktop icon in all the environments I've tested it.
I don't know why gnome thought it was a good idea to make it a big notification instead, but in any case, you should be able to disable them entirely in Mirage with the `alertOnMessageForMsec` setting.

**Comment by rinigus** [comment]
No, it still shows up once in a while after setting alertOnMessageForMsec to zero

**Comment by mirukana** [comment]
https://github.com/mirukana/mirage/commit/379a851a62c849894710795b9cfe3f8cdb623572 from the `dev` branch should fix it, can you confirm? If all good, feel free to close the issue.

**Comment by rinigus** [comment]
there was a silence in the rooms, hence took some time. Thank you for fixing, closing. I'll reopen if it resurfaces
