### ISSUE TITLE
Drawing Wayland Window Titlebars

### ISSUE THREAD

**Issue by theotheroracle** [mirukana/mirage#61]
### Description

when running as a flatpak, the titlebar is missing entirely and the window is not resizable from the window border.

### Your environment
![Screenshot from 2020-06-21 17-08-05](https://user-images.githubusercontent.com/20211219/85236228-cad21300-b3e1-11ea-86f1-106033ffdad3.png)

- Fedora Silverblue 32
-  64bit
- Flatpak, appimage doesn't have this

**Comment by mirukana** [comment]
I suppose you're running GNOME Wayland, does this happen under Xorg?

**Comment by ellietheoracle** [comment]
it doesn't on xorg

**Comment by mirukana** [comment]
The issue is that Wayland doesn't draw titlebars, the GUI toolkit or application has to do it on its own, and Qt doesn't. This will be easy to do when we switch to Qt 5.15+.

The AppImage probably uses Qt's `xcb` (Xorg) rendering plugin instead of `wayland` for some reason, which gets rendered through the XWayland compatibility layer.
You could try forcing behavior in the Flatpak: `flatpak run io.github.mirukana.mirage -platform xcb`

In any case, you can move and resize windows in most desktops simply by holding alt or super and dragging with the left or right mouse button.

**Comment by ellietheoracle** [comment]
could you, as a temporary fix, change the flatpak manifest to enable x11 fallback?
i noticed it's disabled in flatseal
![Screenshot from 2020-06-22 02-37-56](https://user-images.githubusercontent.com/20211219/85261183-6a6ac200-b431-11ea-8635-3212488f3693.png)

**Comment by mirukana** [comment]
Some systems only support pure wayland and not X11 fallback mode. I tried just now `flatpak run io.github.mirukana.mirage -platform xcb` inside a gnome environment and got a window with a titlebar like expected, without changing permissions. Does this not work for you?

**Comment by ellietheoracle** [comment]
> Some systems only support pure wayland and not X11 fallback mode. I tried just now `flatpak run io.github.mirukana.mirage -platform xcb` inside a gnome environment and got a window with a titlebar like expected, without changing permissions. Does this not work for you?

it works, but it's a cumbersome solution, it's a better experience to just disable wayland until the issue is dealt with

**Comment by mirukana** [comment]
If that works better, you can set the `QT_QPA_PLATFORM` environment variable to `xcb` (e.g. in your shell rc or profile) to get the same effect without having to use the argument.
Disabling wayland would kick out users of systems without X11 compatibility, and is a big no-no since I know we have some.
