### ISSUE TITLE
Collapsed side panels usability

### ISSUE THREAD

**Issue by rinigus** [mirukana/mirage#7]
When the window is made narrow, side panels are collapsed to icons (before disappearing). I am not sure whether this mode is that useful. However, if someone likes it, then it should also be possible to make left and right panel full size, by making it the main one. Currently its possible only when the window is too narrow to show icons by moving main pane left/right.

**Comment by ellietheoracle** [comment]
i do like having the collapsed view, but the in between state is sort of useless, i think there should either be a button to collapse it, or even better would be if it could just sort of snap between states .

**Comment by ellietheoracle** [comment]
having all the buttons re-arrange like this is not the best behaviour 
![Screenshot from 2020-06-27 05-38-23](https://user-images.githubusercontent.com/20211219/85920350-83f87900-b838-11ea-86c6-c7347b8ae93c.png)
should the user click on of of the buttons though, the menu should expand, like @rinigus said either to the full size of the view, or it should overlay the chat view if the window is wide enough .

**Comment by mirukana** [comment]
> having all the buttons re-arrange like this is not the best behaviour

How would you have them work when the pane wide enough to show them all in one row?

The left main pane has a minimum width since 0.5.1 so it doesn't get unusable. For the right room pane, I like having it at the current minimum width for the member tab, but true, the other tabs should have a minimum width similar to the main pane and there should be a way to expand members quickly.

**Comment by ellietheoracle** [comment]
> How would you have them work when the pane isn't wide enough to show them all in one row?

like i mentioned above:
> i think there should either be a button to collapse it, or even better would be if it could just sort of snap between states .

**Comment by mirukana** [comment]
Some work on this was done in the dev branch:

- Left pane now auto-expands while the filter field is focused 
- Right pane now auto-expands while one of these condition is true:
  - Member filter field is focused
  - Pane is displaying a member's profile
  - Pane is displaying the room settings
- When the right pane is collapsed, a search/expand button is present at the place where the search field is visible otherwise, clicking on it auto-expands the pane and focuses the field 
- If auto-expanding a pane would make the chat smaller than its normal minimum width, the pane is rendered as an overlay instead
- Once the condition for auto-expansion no longer applies, the pane goes back to its previous size (unless the user dragged to resize it while expanded)

Does this solve the usability problems?

**Comment by theotheroracle** [comment]
looks really nice

**Comment by rinigus** [comment]
There is one corner case that I encountered while testing.

* make window slim enough to have 3 panes available, but left (room list) and right (users list) reduced. In my case, right was showing just icons

* tap on room list. That will make room list an overlay, making current room pane wider and also expand user's list

To me, it feels unnatural. But other than that particular case, it is better for sure.

**Comment by mirukana** [comment]
> * make window slim enough to have 3 panes available, but left (room list) and right (users list) reduced. In my case, right was showing just icons

Added a way to fully hide the right pane and show the icon to bring it back full view: https://github.com/mirukana/mirage/issues/93#issuecomment-658410323

> * tap on room list. That will make room list an overlay, making current room pane wider and also expand user's list

Fixed

**Comment by ixzh** [comment]
hi, how to collapse the left pane(room list pane)?

**Comment by theotheroracle** [comment]
resize the window

**Comment by ixzh** [comment]
> resize the window

haha yeah it works, but can I bind it to a key to toggle it?

**Comment by ixzh** [comment]
This is the best , the  whole pane are hidden. I'm nore talking about the first screenshot in the readme, where left pane are just a column of icons.

![image](https://user-images.githubusercontent.com/14981695/122698574-272c7480-d27a-11eb-858d-3b60c5618d6b.png)
